version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: snowwash_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ammankgk2312
      MYSQL_DATABASE: snowwash_db
    ports:
      - "3306:3306"
    volumes:
      - snowwash_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: snowwash_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Ammankgk2312
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  snowwash_mysql_data:
